### ISSUE TITLE
Conversão das moedas

### ISSUE THREAD

**Issue by welligtonporto** [Personare/back-end-challenge#40]
Boa tarde, tudo bem?

Estou fazendo o desafio seguindo as instruções e surgiu uma pequena dúvida:

Eu posso utilizar um serviço/api externo para me trazer essa conversão considerando a cotação atual das moedas?

Ou devo fazer a conversão de outra forma, como por exemplo considerando alguns valores fixos para as moedas. (ex: $1 = R$5,17, €1 = R$5,58, etc.).

Desde já agradeço sua atenção.

**Comment by caueops** [comment]
Oi @welligtonporto, boa tarde! Como vai?

Primeiramente gostaria de agradecer pelo interesse em nossa vaga e pelo tempo dedicado em realizar o desafio.

Sim, pode utilizar um serviço/api que faça a conversão das moedas. Só um ponto a considerar é que o escopo do projeto pode se tornar bem menor, e levando isso em consideração é importante que você consiga através da implementação mostrar os seus conhecimentos com lógica de programação, orientação a objetos (se aplicável), padrões de projeto, testes automatizados e afins.

A sua dúvida foi sanada?

Grande abraço.

**Comment by welligtonporto** [comment]
Opa @cauealvesbraz, boa tarde! Estou ótimo e espero que estejas bem também.

Entendi, então acredito que estou no caminho certo.

Obrigado pela atenção!
